#!/usr/bin/env php
<?php

// remove execution time limit
set_time_limit(0);

// set memory limit
ini_set('memory_limit', '128M');

require __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Mizmoz\Validate\Console\UpdateCommand;

$application = new Application();

// register the update command
$application->add(new UpdateCommand());

// run
$application->run();
